import type { Metadata } from "next";
import { Inter, Archivo } from "next/font/google";
import "./globals.css";
import "@/app/principal.css";
import BackgroundImage from '@/app/ui/components/BackgroundImage'
import Footer from '@/app/ui/section/Footer'


const inter = Inter({ subsets: ["latin"] });
const archivo =  Archivo({subsets: ["latin"]})
//const whiteNOise = '/images/whiteNoise.jpg'
/*const bkgBody = {
  backgroundImage:`url(${whiteNOise})`,
  backgroundColor:'black',
  backgroundSize:'cover',
  backgroundPosition:'center',
  backgroundRepeat:'no-repeat',
  color:'#000000',
}*/


export const metadata: Metadata = {
  title: "radionudista",
  description: "Generated by felipelabo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${archivo.className} relative min-h-svh`} style={{backgroundColor:'#4e4e4e'}}>
        <BackgroundImage/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
